---
# Playbook for creating a release tag from multiple feature tags

- name: Create Release Tag from Feature Tags
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  vars:
    # Default values that can be overridden in AAP
    source_env: "{{ source_environment | default('sit') }}"
    release_tag: "{{ release_tag_name }}"
    feature_tags: "{{ feature_tag_list | default([]) }}"
    debug_enabled: "{{ debug_mode | default('no') | bool }}"
  tasks:
    - name: Set debug fact
      ansible.builtin.set_fact:
        debug_enabled: "{{ debug_mode | default('no') | bool }}"

    - name: Include common tasks
      ansible.builtin.import_role:
        name: eme_common

    - name: Include verification tasks
      ansible.builtin.import_role:
        name: eme_verification

    - name: Include release creation tasks
      ansible.builtin.import_role:
        name: eme_release_creation
