---
# Playbook for creating a release tag from multiple feature tags

- name: Create Release Tag from Feature Tags
  hosts: "eme-{{ source_env }}"
  gather_facts: false
  vars:
    # Default values that can be overridden in AAP
    source_env: "{{ source_environment | default('sit') }}"
    target_env: "{{ source_env }}"  # For release creation, target is same as source
    release_tag: "{{ release_tag_name }}"
    feature_tags: "{{ feature_tag_list | default([]) }}"
    debug_enabled: "{{ debug_mode | default('no') | bool }}"
  pre_tasks:
    - name: Validate environment names
      ansible.builtin.fail:
        msg: "Invalid environment name. Must be one of: dev, sit, uat"
      when: source_env not in ['dev', 'sit', 'uat']

    - name: Set EME server variables
      ansible.builtin.set_fact:
        eme_source_server: "{{ hostvars['eme-' + source_env]['ansible_host'] }}"
        eme_target_server: "{{ eme_source_server }}"  # For release creation, target is same as source

  tasks:
    - name: Set debug fact
      ansible.builtin.set_fact:
        debug_enabled: "{{ debug_mode | default('no') | bool }}"

    - name: Include common tasks
      ansible.builtin.import_role:
        name: eme_common

    - name: Include release creation tasks
      ansible.builtin.import_role:
        name: eme_release_creation
