---
# Handlers for EME common tasks

- name: Clean up temporary files on source EME
  ansible.builtin.file:
    path: "{{ temp_dir }}"
    state: absent
  delegate_to: "{{ eme_source_server }}"
  listen: cleanup_all

- name: Clean up temporary files on target EME
  ansible.builtin.file:
    path: "{{ temp_dir }}"
    state: absent
  delegate_to: "{{ eme_target_server }}"
  listen: cleanup_all

- name: Clean up temporary files on control node
  ansible.builtin.file:
    path: "{{ temp_dir }}"
    state: absent
  delegate_to: localhost
  listen: cleanup_all
